// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://goqzkutcfnwiuribetuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvcXprdXRjZm53aXVyaWJldHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzcyNjMsImV4cCI6MjA2NjI1MzI2M30.6QbFckVK-DFHLK0UgI8ajvzPDaazBE9zROG4sn9uN28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);