// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://biejhivwsnaqrjlbssdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpZWpoaXZ3c25hcXJqbGJzc2RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MzEwMjQsImV4cCI6MjA2NjQwNzAyNH0.uIhq8wuB6buGwxr1uOt9Mxk9wqpYJtG0Zy-cqaT_zDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);